### ISSUE TITLE
Method not allowed on creating a snapshot

### ISSUE THREAD

**Issue by DenTray** [ArchiveLabs/api.archivelab.org#15]
There is an issue on creating snapshots through `POST https://api.archivelab.org/v1/pragma` route.

This call doesn't work on `Try It Out` form too.

![image](https://user-images.githubusercontent.com/9486872/50482949-8abfe900-0a13-11e9-8381-a82bd6ced434.png)

**Comment by mekarpeles** [comment]
Does it work when you call directly against pragma.archivelab.org?
a la https://github.com/archivelabs/pragma.archivelab.org

**Comment by mekarpeles** [comment]
No space left on the VM disk! Working on it, thanks for raising this issue :)

**Comment by DenTray** [comment]
@mekarpeles any updates here?

**Comment by mekarpeles** [comment]
This is hopefully fixed now! Sorry about the wait!

best wishes,

- mek

https://mek.fyi
Citizen of the World
Open Librarian @ openlibrary.org

**Comment by DenTray** [comment]
Unfortunately, it still returns 405 error on this page https://archive.readme.io/docs/creating-a-snapshot

<img width="915" alt="image" src="https://user-images.githubusercontent.com/9486872/57310866-620bd680-710c-11e9-8b71-fa5a27aceea2.png">

**Comment by mekarpeles** [comment]
It's possible that UI is wrong

Does the `curl` in this section work for you?
https://github.com/archiveLabs/pragma.archivelab.org#creating-an-annotation

best wishes,

- mek

https://mek.fyi
Citizen of the World
Open Librarian @ openlibrary.org

**Comment by mekarpeles** [comment]
`curl -X POST -H "Content-Type: application/json" -d '{"url": "https://sumally.com/p/740500", "annotation": {"id": "lst-ib", "message": "Theres a microphone button in the searchbox"}}' https://pragma.archivelab.org` this seems to work for me

**Comment by mekarpeles** [comment]
url of endpoint updated, should be fixed both in the API and the UI/docs now.

![Screen Shot 2019-05-09 at 11 24 54AMPDT](https://user-images.githubusercontent.com/978325/57477250-26c4f100-724d-11e9-9833-774c084e6006.png)
